name: Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: write

jobs:
  playwright:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/python:v1.62.0-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Verify installation
        run: |
          python --version
          python -m pip list
          python -m pytest --version

      - name: Run tests
#        run: python -m pytest --junitxml=reports/junit.xml
        run: python -m pytest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: reports/
          retention-days: 7

      - name: Notify n8n
        run: |
          curl -X POST \
            https://straining-unsliced-creed.ngrok-free.dev/webhook-test/playwright-report \
            -H "Content-Type: application/json" \
            -d '{
              "repository":"${{ github.repository }}",
              "run_id":"${{ github.run_id }}"
            }'
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: reports/allure-results
          gh_pages: true
          allure_history: allure-history

      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Send Results to n8n
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            --data @playwright-reports \
            https://straining-unsliced-creed.ngrok-free.dev/webhook-test/playwright-report